### YamlMime:PowershellCmdlet
summary: |-
  **Relevant for:** AIP unified labeling client only

  Sets optional configurations for the Network Discovery service.
module: AzureInformationProtection
notes: ""
inputs:
- name: <xref href="None" data-throw-if-not-resolved="False" />
  description: ""
outputs:
- name: <xref href="System.Object" data-throw-if-not-resolved="False" />
  description: ""
links:
- text: Get-MIPNetworkDiscoveryConfiguration
  href: Get-MIPNetworkDiscoveryConfiguration.yml
- text: Get-MIPNetworkDiscoveryJobs
  href: Get-MIPNetworkDiscoveryJobs.yml
- text: Get-MIPNetworkDiscoveryStatus
  href: Get-MIPNetworkDiscoveryStatus.yml
- text: Import-MIPNetworkDiscoveryConfiguration
  href: Import-MIPNetworkDiscoveryConfiguration.yml
- text: Install-MIPNetworkDiscovery
  href: Install-MIPNetworkDiscovery.yml
- text: Set-MIPNetworkDiscovery
  href: Set-MIPNetworkDiscovery.yml
- text: Start-MIPNetworkDiscovery
  href: Start-MIPNetworkDiscovery.yml
- text: Uninstall-MIPNetworkDiscovery
  href: Uninstall-MIPNetworkDiscovery.yml
syntaxes:
- Set-MIPNetworkDiscoveryConfiguration [-OnlineConfiguration <OnlineConfiguration>] [<CommonParameters>]
examples:
- title: 'Example 1: Set the Network Discovery service to use online configuration'
  code: |-
    powershell
    PS C:\> Set-AIPScannerConfiguration -OnlineConfiguration On

    Configuration was set successfully.
  description: |-
    This command sets the Network Discovery service to get its configuration directly from the settings configured online in the Azure portal.
  summary: ""
parameters:
- type: <xref href="OnlineConfiguration" data-throw-if-not-resolved="False" />
  name: OnlineConfiguration
  description: |+
    Specifies whether the scanner gets its configuration settings directly from the Azure portal, or uses an offline configuration file.

    - **On:** The default setting. The scanner gets its configuration settings directly from the Azure portal.

    - **Off:** The Network Discovery service is prevented from getting its configuration settings directly from the Azure portal. Instead, the scanner is configured by settings that you import from a file. 

    If the scanner cannot support online configuration, you must still configure the network scan jobs in the Azure portal. Then, export the network scan job configuration from the portal to a **.json** file and import this file by using the [Import-**Import-MIPNetworkDiscoveryConfiguration**](./Import-MIPNetworkDiscoveryConfiguration.yml) cmdlet.

  defaultValue: None
  position: Named
  aliases: ""
  parameterValueGroup: On, Off
uid: AzureInformationProtection.Set-MIPNetworkDiscoveryConfiguration
name: Set-MIPNetworkDiscoveryConfiguration
description: |-
  The **Set-MIPNetworkDiscoveryConfiguration** cmdlet sets local configuration settings for the Network Discovery service.

  The Network Discovery service manages network scan jobs, and enables Azure Information Protection administrators to scan specific IP addresses or ranges for risky repositories. Administrators may want to add these repositories to content scan jobs and scan their content further.

  While most of the network scan job settings are configured in the Azure portal, you must use this cmdlet if you need to import configuration settings from a file because the deployment cannot support online configuration.

  Any changes will be used the next time the network scan jobs run. If you need the changes to take effect immediately, restart the Network Discovery service on the Windows server computer.
metadata:
  external help file: AIP.dll-Help.xml
  Module Name: AzureInformationProtection
  online version: https://go.microsoft.com/fwlink/?linkid=2137527
  schema: 2.0.0
